# Generated by Django 5.0.6 on 2024-06-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0002_book_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookauthor',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
